name: Node.name:Telegram_Bot_Auto_Run

on:
  push:
    branches: [ main ]

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Start Bot
      run: node index.js
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
